SmartCore\Bundle\EngineBundle\Entity\Block:
    properties:
        pos:
            - NotBlank: ~
            - Type:
                  type: integer
                  message: число не является целым
