imports:
    - { resource: '@SiteBundle/Resources/config/config.yml', ignore_errors: true }
    - { resource: '@SiteBundle/Resources/config/security.yml', ignore_errors: true }

#framework:
#    validation:
#        cache: apc

doctrine:
    orm:
        metadata_cache_driver: %orm_cache_driver%
        result_cache_driver: %orm_cache_driver%
        query_cache_driver: %orm_cache_driver%

monolog:
    handlers:
        security:
            # log all messages (since debug is the lowest level)
            level:    debug
            type:     stream
            path:     "%kernel.logs_dir%/security.log"
            channels: [ security ]
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels:     ['!security']
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
