imports:
    - { resource: '@SiteBundle/Resources/config/config.yml', ignore_errors: true }
    - { resource: '@SiteBundle/Resources/config/security.yml', ignore_errors: true }

#framework:
#    validation:
#        cache: apc

doctrine:
    orm:
        metadata_cache_driver: "%orm_cache_driver%"
        result_cache_driver: "%orm_cache_driver%"
        query_cache_driver: "%orm_cache_driver%"

monolog:
    handlers:
        security:
            level:    warning
            type:     stream
            path:     "%kernel.logs_dir%/security.log"
            channels: [ security ]
        request:
            level:    warning
            type:     stream
            path:     "%kernel.logs_dir%/request.log"
            channels: [ request ]
        translation:
            level:    warning
            type:     stream
            path:     "%kernel.logs_dir%/translation.log"
            channels: [ translation ]
        main:
            type:         fingers_crossed
            action_level: warning # error
            handler:      nested
            channels:     ['!security', '!event', '!request', '!translation']
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
