
cmf_hello:
    path: /hi/
    defaults:
        _controller: SmartCoreEngineBundle:Hello:index

cmf_admin:
    resource: "routing_admin.yml"
    prefix: /admin/

# AJAX
#sc_engine_ajax_invalid:
#    path: /ajax
#    defaults:
#        _controller: SmartCoreEngineBundle:Ajax:invalid
#sc_engine_ajax_invalid2:
#    path: /ajax/
#    defaults:
#        _controller: SmartCoreEngineBundle:Ajax:invalid
#sc_engine_ajax_node_index:
#    path: /ajax/{node_id}/
#    defaults:
#        _controller: SmartCoreEngineBundle:Ajax:node
#        slug: ""
#    requirements:
#        slug: ".+"
#        node_id: \d+
#sc_engine_ajax_node:
#    path: /ajax/{node_id}/{slug}
#    defaults:
#        _controller: SmartCoreEngineBundle:Ajax:node
#        slug: ""
#    requirements:
#        slug: ".+"
#        node_id: \d+
#sc_engine_ajax_index:
#    path: /ajax/{object}/
#    defaults:
#        _controller: SmartCoreEngineBundle:Ajax:run
#sc_engine_ajax:
#    path: /ajax/{object}/{slug}
#    defaults:
#        _controller: SmartCoreEngineBundle:Ajax:run
#        slug: ""
#    requirements:
#        slug: ".+"

# NODE MAPPER
cmf_node_mapper:
    path: /{slug}
    methods: GET
    defaults:
        _controller: SmartCoreEngineBundle:Engine:run
        slug: ""
    requirements:
        slug: ".+"
cmf_node_postprocessor:
    path: /{slug}
    methods: POST
    defaults:
        _controller: SmartCoreEngineBundle:Engine:post
        slug: ""
    requirements:
        slug: ".+"
