cms_admin_system:
    path: /
    defaults:
        _controller: CMSBundle:Admin:notFound

cms_admin_backup_download:
    path: /backup/{filename}
    defaults:
        _controller: CMSBundle:Admin:backupDownload
        slug: '.+'

cms_admin_backup:
    path: /backup/
    defaults:
        _controller: CMSBundle:Admin:backupIndex

# Structure
cms_admin_structure:
    path: /structure/
    defaults:
        _controller: CMSBundle:AdminStructure:structure

cms_admin_structure_trash:
    path: /structure/trash/
    defaults:
        _controller: CMSBundle:AdminStructure:trash

cms_admin_structure_trash_restore_node:
    path: /structure/trash/restore_node/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:trashRestoreNode

cms_admin_structure_trash_purge_node:
    path: /structure/trash/purge_node/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:trashPurgeNode

cms_admin_structure_trash_restore_folder:
    path: /structure/trash/restore_folder/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:trashRestoreFolder

cms_admin_structure_trash_purge_folder:
    path: /structure/trash/purge_folder/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:trashPurgeFolder

# Region
cms_admin_structure_region:
    path: /structure/region/
    defaults:
        _controller: CMSBundle:AdminStructure:regionIndex

cms_admin_structure_region_edit:
    path: /structure/region/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:regionEdit
    requirements:
        id: \d+

# Folder
cms_admin_structure_folder_create:
    path: /structure/folder/create/
    defaults:
        _controller: CMSBundle:AdminStructure:folderCreate
        parent: 1

cms_admin_structure_folder_create_in_folder:
    path: /structure/folder/create/{parent}/
    defaults:
        _controller: CMSBundle:AdminStructure:folderCreate
    requirements:
        parent: \d+

cms_admin_structure_folder:
    path: /structure/folder/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:folderEdit
    requirements:
        id: \d+

# Node
cms_admin_structure_node_create:
    path: /structure/node/create/
    defaults:
        _controller: CMSBundle:AdminStructure:nodeCreate

cms_admin_structure_node_create_in_folder:
    path: /structure/node/create/{folder_pid}/
    defaults:
        _controller: CMSBundle:AdminStructure:nodeCreate

#cms_admin_structure_node_all:
#    path: /structure/node/
#    defaults:
#        _controller: CMSBundle:AdminStructure:node

cms_admin_structure_node_properties:
    path: /structure/node/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:nodeEdit
    requirements:
        id: \d+

# Appearance
cms_admin_appearance:
    path: /appearance/
    defaults:
        _controller: CMSBundle:AdminAppearance:index

cms_admin_appearance_template:
    path: /appearance/{name}.twig/
    defaults:
        _controller: CMSBundle:AdminAppearance:templateEdit

cms_admin_appearance_template_history:
    path: /appearance/{name}.twig/history/
    defaults:
        _controller: CMSBundle:AdminAppearance:templateHistory

cms_admin_appearance_style_history:
    path: /appearance/{name}/history/
    defaults:
        _controller: CMSBundle:AdminAppearance:styleHistory

cms_admin_appearance_history_code:
    path: /appearance/history/{id}/
    defaults:
        _controller: CMSBundle:AdminAppearance:historyCode

cms_admin_appearance_history_rollback:
    path: /appearance/history/rollback/{id}/
    defaults:
        _controller: CMSBundle:AdminAppearance:historyRollback

cms_admin_appearance_style:
    path: /appearance/{name}/
    defaults:
        _controller: CMSBundle:AdminAppearance:styleEdit

cms_admin_files:
    path: /files/
    defaults:
        _controller: CMSBundle:Admin:elfinder

# Users
cms_admin_user:
    path: /user/
    defaults:
        _controller: CMSBundle:AdminUser:index

cms_admin_user_create:
    path: /user/create/
    defaults:
        _controller: CMSBundle:AdminUser:create

cms_admin_user_roles:
    path: /user/roles/
    defaults:
        _controller: CMSBundle:AdminUser:roles

cms_admin_user_role_edit:
    path: /user/role/{id}/
    defaults:
        _controller: CMSBundle:AdminUser:roleEdit

cms_admin_user_edit:
    path: /user/{id}/
    defaults:
        _controller: CMSBundle:AdminUser:edit

# Configuration

cms_admin_config_media:
    path: /config/media/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:index

cms_admin_config_media_create_storage:
    path: /config/media/storage_create/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:createStorage

cms_admin_config_media_edit_storage:
    path: /config/media/storage_{id}/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:editStorage
    requirements:
        id: \d+

cms_admin_config_media_create_collection:
    path: /config/media/collection_create/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:createCollection

cms_admin_config_media_edit_collection:
    path: /config/media/collection_{id}/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:editCollection
    requirements:
        id: \d+

admin_settings:
    resource: '@SmartSettingsBundle/Resources/config/routing.yml'
    prefix:   /config/
