# ADMIN
sc_engine_admin_index:
    pattern: /admin/
    defaults:
        _controller: SmartCoreEngineBundle:Admin:index
sc_engine_admin:
    pattern: /admin/{slug}
    defaults:
        _controller: SmartCoreEngineBundle:Admin:run
        slug: ""
    requirements:
        slug: ".+"
# ACTION        
sc_engine_action_index:
    pattern: /action/{node_id}/
    defaults:
        _controller: SmartCoreEngineBundle:Action:run
    requirements:
        node_id: \d+
sc_engine_action:
    pattern: /action/{node_id}/{slug}
    defaults:
        _controller: SmartCoreEngineBundle:Action:run
    defaults:
        slug: ""
    requirements:
        slug: ".+"
        node_id: \d+
sc_engine_action_invalid_index:
    pattern: /action/
    defaults:
        _controller: SmartCoreEngineBundle:Action:invalid
sc_engine_action_invalid:
    pattern: /action/{slug}
    defaults:
        _controller: SmartCoreEngineBundle:Action:invalid
        slug: ""
    requirements:
        slug: ".+"
# AJAX
sc_engine_ajax_invalid:
    pattern: /ajax
    defaults:
        _controller: SmartCoreEngineBundle:Ajax:invalid
sc_engine_ajax_invalid2:
    pattern: /ajax/
    defaults:
        _controller: SmartCoreEngineBundle:Ajax:invalid
sc_engine_ajax_node_index:
    pattern: /ajax/{node_id}/
    defaults:
        _controller: SmartCoreEngineBundle:Ajax:node
        slug: ""    
    requirements:
        slug: ".+"    
        node_id: \d+
sc_engine_ajax_node:
    pattern: /ajax/{node_id}/{slug}
    defaults:
        _controller: SmartCoreEngineBundle:Ajax:node
        slug: ""    
    requirements:
        slug: ".+"    
        node_id: \d+
sc_engine_ajax_index:
    pattern: /ajax/{object}/
    defaults:
        _controller: SmartCoreEngineBundle:Ajax:run
sc_engine_ajax:
    pattern: /ajax/{object}/{slug}
    defaults:
        _controller: SmartCoreEngineBundle:Ajax:run
        slug: ""
    requirements:
        slug: ".+"
# robots.txt
sc_engine_robots_txt:
    pattern: /robots.txt
    defaults:
        _controller: SmartCoreEngineBundle:RobotsTxt:index
# NODE MAPPER
sc_engine_node_mapper:
    pattern: /{slug}
    defaults:
        _controller: SmartCoreEngineBundle:NodeMapper:index
        slug: ""
    requirements:
        _method:  GET
        slug: ".+"
sc_engine_node_postprocessor:
    pattern: /{slug}
    defaults:
        _controller: SmartCoreEngineBundle:PostProcessor:index
        slug: ""
    requirements:
        _method:  POST
        slug: ".+"
    