
cms_api:
    resource: 'routing_api.yml'
    prefix: /api/

cms_admin:
    resource: 'routing_admin.yml'
    prefix: /%admin_path%/

cms_admin_module_routes:
    resource: .
    type: module_admin

# ... other
cms_admin_404:
    path: /%admin_path%/{slug}
    defaults:
        _controller: CMSBundle:Admin:notFound
        slug: ''
    requirements:
        slug: '.+'

cms_getprocessor:
    path: /{slug}
    methods: GET
    defaults:
        _controller: CMSBundle:Engine:run
        slug: ''
    requirements:
        slug: '.+'

cms_postprocessor:
    path: /{slug}
    methods: POST
    defaults:
        _controller: CMSBundle:Engine:post
        slug: ''
    requirements:
        slug: '.+'

# Эти маршруты нужны для генерации ссылок к модулям с учетом пути, куда они подключены.
cms_modules:
    resource: .
    type: modules_enabled
