
cms_api:
    path: /
    defaults:
        _controller: CMSBundle:ApiEngine:notFound

cms_api_node_index:
    path: /{node_id}/
    defaults:
        _controller: CMSBundle:ApiEngine:node
        slug: ''
    requirements:
        node_id: \d+

cms_api_node:
    path: /{node_id}/{slug}
    defaults:
        _controller: CMSBundle:ApiEngine:node
        slug: ''
    requirements:
        slug: '.+'
        node_id: \d+

cms_api_not_found:
    path: /{slug}
    defaults:
        _controller: CMSBundle:ApiEngine:notFound
        slug: ''
    requirements:
        slug: '.+'
