
cms_admin_index:
    path: /
    defaults:
        _controller: CMSBundle:Admin:index

# Security
#cms_admin_login:
#    path: /login
#    defaults:
#        _controller: FrameworkBundle:Template:template
#        template: 'CMSBundle:User:login.html.twig'

cms_admin_logout:
    path: /logout
    defaults:
        _controller: FOSUserBundle:Security:logout

cms_admin_system:
    resource: 'routing_admin_system.yml'
    prefix: /system/

cms_admin_reports:
    path: /reports/
    defaults:
        _controller: CMSBundle:Admin:reports

cms_admin_node:
    path: /node/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:node
    requirements:
        id: \d+

cms_admin_node_w_slug:
    path: /node/{id}/{slug}
    defaults:
        _controller: CMSBundle:AdminStructure:node
    requirements:
        id: \d+
        slug: '.+'

#cms_admin_module_full_path:
#    path: /{name}/
#    defaults:
#        _controller: CMSBundle:Admin:module

# Modules @todo убрать в system.
cms_admin_module:
    path: /module/
    defaults:
        _controller: CMSBundle:Admin:module

cms_admin_module_install_updatedb:
    path: /module/install/updatedb
    methods: 'POST'
    defaults:
        _controller: CMSBundle:Admin:moduleInstallUpdateDb

cms_admin_module_install:
    path: /module/install/{filename}
    defaults:
        _controller: CMSBundle:Admin:moduleInstall
        filename: ''

# @todo
cms_admin_help:
    path: /help/
    defaults:
        _controller: CMSBundle:Admin:notFound
