# ADMIN
sc_engine_admin_index:
    pattern: /admin/
    defaults:
        _controller: SmartCore\CMF\Admin::indexAction
sc_engine_admin:
    pattern: /admin/{slug}
    defaults:
        _controller: SmartCore\CMF\Admin::runAction
        slug: ""
    requirements:
        slug: ".+"
# ACTION        
sc_engine_action_index:
    pattern: /action/{node_id}/
    defaults:
        _controller: SmartCore\CMF\Action::runAction
    requirements:
        node_id: \d+
sc_engine_action:
    pattern: /action/{node_id}/{slug}
    defaults:
        _controller: SmartCore\CMF\Action::runAction
    defaults:
        slug: ""
    requirements:
        slug: ".+"
        node_id: \d+
sc_engine_action_invalid_index:
    pattern: /action/
    defaults:
        _controller: SmartCore\CMF\Action::invalidAction
sc_engine_action_invalid:
    pattern: /action/{slug}
    defaults:
        _controller: SmartCore\CMF\Action::invalidAction
        slug: ""
    requirements:
        slug: ".+"
# AJAX
sc_engine_ajax_invalid:
    pattern: /ajax
    defaults:
        _controller: SmartCore\CMF\Ajax::invalidAction
sc_engine_ajax_invalid2:
    pattern: /ajax/
    defaults:
        _controller: SmartCore\CMF\Ajax::invalidAction
sc_engine_ajax_node_index:
    pattern: /ajax/{node_id}/
    defaults:
        _controller: SmartCore\CMF\Ajax::nodeAction
        slug: ""    
    requirements:
        slug: ".+"    
        node_id: \d+
sc_engine_ajax_node:
    pattern: /ajax/{node_id}/{slug}
    defaults:
        _controller: SmartCore\CMF\Ajax::nodeAction
        slug: ""    
    requirements:
        slug: ".+"    
        node_id: \d+
sc_engine_ajax_index:
    pattern: /ajax/{object}/
    defaults:
        _controller: SmartCore\CMF\Ajax::runAction
sc_engine_ajax:
    pattern: /ajax/{object}/{slug}
    defaults:
        _controller: SmartCore\CMF\Ajax::runAction
        slug: ""
    requirements:
        slug: ".+"
# robots.txt
sc_engine_robots_txt:
    pattern: /robots.txt
    defaults:
        _controller: SmartCore\CMF\RobotsTxt::indexAction
# NODE MAPPER
sc_engine_node_mapper:
    pattern: /{slug}
    defaults:
        _controller: SmartCoreEngineBundle:NodeMapper:index
        slug: ""
    requirements:
        _method:  GET
        slug: ".+"
sc_engine_node_postprocessor:
    pattern: /{slug}
    defaults:
        _controller: SmartCoreEngineBundle:PostProcessor:index
        slug: ""
    requirements:
        _method:  POST
        slug: ".+"
    