parameters:
#    smart_core_engine.example.class: SmartCore\Bundle\EngineBundle\Example

services:
#    smart_core_engine.example:
#        class: %smart_core_engine.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
