services:
    db.logger:
        class: Doctrine\DBAL\Logging\DebugStack
# Listeners
    engine.controller.listener:
        class: SmartCore\Bundle\EngineBundle\Listener\ModuleControllerModifier
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onController }
    engine.request.listener:
        class: SmartCore\Bundle\EngineBundle\Listener\ModuleControllerModifier
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
    engine.response.listener:
        class: SmartCore\Bundle\EngineBundle\Listener\ModuleControllerModifier
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }
    engine.view.listener:
        class: SmartCore\Bundle\EngineBundle\Listener\ModuleControllerModifier
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onView }
    engine.db.table_prefix_subscriber:
        class: SmartCore\Bundle\EngineBundle\Listener\TablePrefixSubscriber
        arguments: [%database_table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
# Core
    engine.breadcrumbs:
        class: SmartCore\Bundle\EngineBundle\Engine\Breadcrumbs
    engine.context:
        class: SmartCore\Bundle\EngineBundle\Engine\EngineContext
        arguments: [ @service_container ]
    engine.folder:
        class: SmartCore\Bundle\EngineBundle\Engine\Folder
        arguments: [ @service_container ]
    engine.module_manager:
        class: SmartCore\Bundle\EngineBundle\Engine\ModuleManager
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ initialize ]
    engine.cache:
        class: SmartCore\Bundle\EngineBundle\Engine\Cache
        arguments: [ @kernel ]
    engine.node_manager:
        class: SmartCore\Bundle\EngineBundle\Engine\NodeManager
        arguments: [ @engine.db, %database_table_prefix%, @doctrine.orm.entity_manager, @engine.context, @kernel ]
    engine.permissions:
        class: SmartCore\Bundle\EngineBundle\Engine\Permissions
        arguments: [ @service_container ]
    engine.theme:
        class: SmartCore\Bundle\EngineBundle\Engine\Theme
        calls:
            - [ setContainer, [ @service_container ] ]
    engine.jslib:
        class: SmartCore\Bundle\EngineBundle\Engine\JavaScriptLibrary
        arguments: [ @engine.db ]
        calls:
            - [ setContainer, [ @service_container ] ]
    engine.user:
        class: SmartCore\Bundle\EngineBundle\Engine\User
        arguments: [ @service_container ]
    engine.toolbar:
        class: SmartCore\Bundle\EngineBundle\Engine\Toolbar
        calls:
            - [ setContainer, [ @service_container ] ]
# Forms
    engine.form.type.extension.node_id:
        class: SmartCore\Bundle\EngineBundle\Form\Extension\FormTypeNodeIdExtension
        arguments: [ @engine.context ]
        tags:
            - { name: form.type_extension, alias: form }
    engine.form.type.folder_tree:
        class: SmartCore\Bundle\EngineBundle\Form\Tree\FolderTreeType
        arguments: [ @doctrine ]
        tags:
            - { name: form.type, alias: folder_tree }
# Menu selected items
    cmf_admin.menu.voter.request:
        class: SmartCore\Bundle\EngineBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
# Aliases
    engine.db:
        alias: database_connection        
#    engine.settings:
#        alias: service_container
