parameters:
    router.class: SmartCore\Bundle\CMSBundle\Router\NodeRouter
    router.options.generator_dumper_class: SmartCore\Bundle\CMSBundle\Router\PhpGeneratorDumper

services:
# Core
    cms.breadcrumbs:
        class: SmartCore\Bundle\CMSBundle\Tools\Breadcrumbs
    cms.region:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineRegion
        arguments: [ @doctrine.orm.default_entity_manager, @form.factory ]
    cms.context:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineContext
        arguments: [ @request_stack ]
    cms.folder:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineFolder
        arguments: [ @service_container ]
    cms.module:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineModule
        arguments: [ @kernel ]
    cms.node:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineNode
        arguments:
            - @doctrine.orm.default_entity_manager
            - @form.factory
            - @kernel
            - @cms.context
            - @tagcache
    cms.router:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineRouter
        calls:
            - [ setContainer, [ @service_container ] ]
    cms.routes.module_admin.loader:
        class: SmartCore\Bundle\CMSBundle\Router\ModuleAdminRoutesLoader
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setResolver,  [ @routing.resolver ] ]
        tags:
            - { name: routing.loader }
    cms.routes.modules.loader:
        class: SmartCore\Bundle\CMSBundle\Router\ModuleRoutesLoader
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setResolver,  [ @routing.resolver ] ]
        tags:
            - { name: routing.loader }
    cms.toolbar:
        class: SmartCore\Bundle\CMSBundle\Engine\EngineToolbar
        calls:
            - [ setContainer, [ @service_container ] ]
# Listeners
    cms.controller.listener:
        class: SmartCore\Bundle\CMSBundle\Listener\ModuleControllerModifierListener
        arguments: [ @cms.context, @cms.folder, @cms.module, @cms.node, @twig.loader ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onController }
    cms.request.listener:
        class: SmartCore\Bundle\CMSBundle\Listener\ModuleControllerModifierListener
        arguments: [ @cms.context, @cms.folder, @cms.module, @cms.node, @twig.loader ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
    cms.response.listener:
        class: SmartCore\Bundle\CMSBundle\Listener\ModuleControllerModifierListener
        arguments: [ @cms.context, @cms.folder, @cms.module, @cms.node, @twig.loader ]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }
    cms.view.listener:
        class: SmartCore\Bundle\CMSBundle\Listener\ModuleControllerModifierListener
        arguments: [ @cms.context, @cms.folder, @cms.module, @cms.node, @twig.loader ]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onView }
    cms.db.table_prefix_subscriber:
        class: SmartCore\Bundle\CMSBundle\Listener\TablePrefixSubscriber
        arguments: [ %database_table_prefix% ]
        public: false
        tags:
            - { name: doctrine.event_subscriber }
    cms.folder.doctrine_subscriber:
        class: SmartCore\Bundle\CMSBundle\Listener\FolderDoctrineSubscriber
        arguments: [ @service_container ]
        public: false
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
# Forms
    cms.form.type.extension.node_id:
        class: SmartCore\Bundle\CMSBundle\Form\Extension\FormTypeNodeIdExtension
        arguments: [ @cms.context ]
        tags:
            - { name: form.type_extension, alias: form }
    cms.form.type.folder_tree:
        class: SmartCore\Bundle\CMSBundle\Form\Tree\FolderTreeType
        arguments: [ @doctrine ]
        tags:
            - { name: form.type, alias: cms_folder_tree }
    cms.form.type.user:
        class: SmartCore\Bundle\CMSBundle\Form\Type\UserFormType
        arguments: [ @doctrine.orm.default_entity_manager ]
        tags:
            - { name: form.type, alias: smart_core_cms_user }
    cms.form.registration.admin.factory:
        class: FOS\UserBundle\Form\Factory\FormFactory
        arguments: [ @form.factory, %fos_user.registration.form.name%, 'smart_core_cms_user', %fos_user.registration.form.validation_groups% ]
    cms.form.profile.admin.factory:
        class: FOS\UserBundle\Form\Factory\FormFactory
        arguments: [ @form.factory, %fos_user.profile.form.name%, 'smart_core_cms_user', %fos_user.profile.form.validation_groups% ]

# Twig
    cms.twig.extension:
        class: SmartCore\Bundle\CMSBundle\Twig\CmsExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }
    cms.twig.html_title_extension:
        class: SmartCore\Bundle\CMSBundle\Twig\HtmlTitleExtension
        arguments: [ @cms.breadcrumbs, @settings ]
        tags:
            - { name: twig.extension }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
# Menu selected items
    cms.menu.voter.request:
        class: SmartCore\Bundle\CMSBundle\Menu\RequestVoter
        arguments:
            - @request_stack
            - %admin_path%
        tags:
            - { name: knp_menu.voter }
