#parameters:
#    smart_core_engine.example.class: SmartCore\Bundle\EngineBundle\Example

services:
    db:
        alias: database_connection
    db.logger:
        class: Doctrine\DBAL\Logging\DebugStack
#    engine.site:
#        class: SmartCore\Bundle\EngineBundle\
#    smart_core_engine.example:
#        class: %smart_core_engine.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
