#parameters:
#    smart_core_engine.example.class: SmartCore\Bundle\EngineBundle\Example

services:
    engine.controller.listener:
        class: SmartCore\Bundle\EngineBundle\Listener\ModuleControllerModifier
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onController }
    engine.request.listener:
        class: SmartCore\Bundle\EngineBundle\Listener\ModuleControllerModifier
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
    engine.view.listener:
        class: SmartCore\Bundle\EngineBundle\Listener\ModuleControllerModifier
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onView }
    db.logger:
        class: Doctrine\DBAL\Logging\DebugStack
    engine.breadcrumbs:
        class: SmartCore\Bundle\EngineBundle\Templater\Helper\Breadcrumbs
    engine.env:
        class: SmartCore\Bundle\EngineBundle\Service\Environment
        arguments: [ @service_container ]
    engine.folder:
        class: SmartCore\Bundle\EngineBundle\Service\Folder
        calls:
            - [ setContainer, [ @service_container ] ]
    engine.block:
        class: SmartCore\Bundle\EngineBundle\Engine\Block
        calls:
            - [ setContainer, [ @service_container ] ]
    engine.module:
        class: SmartCore\Bundle\EngineBundle\Engine\Module
        calls:
            - [ setContainer, [ @service_container ] ]
    engine.node:
        class: SmartCore\Bundle\EngineBundle\Engine\Node
        calls:
            - [ setContainer, [ @service_container ] ]
    engine.permissions:
        class: SmartCore\Bundle\EngineBundle\Engine\Permissions
        arguments: [ @service_container ]
    engine.theme:
        class: SmartCore\Bundle\EngineBundle\Engine\Theme
        calls:
            - [ setContainer, [ @service_container ] ]
    engine.jslib:
        class: SmartCore\Bundle\EngineBundle\Engine\JavaScriptLibrary
        arguments: [ @engine.db ]
        calls:
            - [ setContainer, [ @service_container ] ]
    engine.html:
        class: SmartCore\Bundle\EngineBundle\Templater\Helper\Html
    engine.site:
        class: SmartCore\Bundle\EngineBundle\Service\Site
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ init ]
    engine.settings:
        alias: service_container        
    engine.user:
        class: SmartCore\Bundle\EngineBundle\Engine\User
        arguments: [ @service_container ]
    engine.db.table_prefix_subscriber:
        class: SmartCore\Bundle\EngineBundle\Listener\TablePrefixSubscriber
        arguments: [%database_table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }

# Aliases
    engine.db:
        alias: database_connection        
    engine.environment:
        alias: engine.env

#    smart_core_engine.example:
#        class: %smart_core_engine.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
