appearance_editor:
    type: ChoiceType
    choices:
        ace: ace
        codemirror: codemirror
    value: ace
appearance_editor_theme: idle_fingers
html_title_delimiter: '&ndash;'
site_full_name: Smart Core CMS (based on Symfony2 Framework)
site_short_name: Smart Core CMS
twitter_bootstrap_version:
    type: ChoiceType
    choices:
        2: 2
        3: 3
    value: 3
timezone:
    #title: Timezone
    type: TimezoneType
    value: Europe/Moscow
