appearance_editor:
    type: ChoiceType
    choices:
        ace: Ace
        codemirror: Codemirror
    value: ace
    personalize: true
appearance_editor_theme: idle_fingers
html_title_delimiter: '&ndash;'
site_full_name: Smart Core CMS (based on Symfony2 Framework)
site_short_name: Smart Core CMS
twitter_bootstrap_version:
    type: ChoiceType
    choices:
        2: v2.3.2
        3: v3.3.7
    value: 3
timezone:
    #title: Timezone
    type: TimezoneType
    value: Europe/Moscow
languages:
    type: ChoiceType
    expanded: true
    multiple: true
    description: Проверка мльтиселекта.
    choices:
        ru: Русский
        en: Английский
    value: [ru]
    personalize: true
test_param:
    value: 123
    hidden: true
